states:
  - 'X':
    value:
      initial: 122.0
      goal: [65.0]
      range: [0.0, 141.0]
      overflow: 'break'
    implicit_grid:
      active: true
      resolution: 1.0
      size: 141
    control:
      - add :
        - 'X'
        - multiply:
          - cosine: 
            - 'W'
          - 'V'
          - 'sample_time_increment'
  - 'Y':
    value:
      initial: 20.0
      goal: [65.0]
      range: [0.0, 141.0]
      overflow: 'break'
    implicit_grid:
      active: true
      resolution: 1.0
      size: 141
    control:
      - add:
        - 'Y'
        - multiply:
          - sine: 
            - 'W'
          - 'V'
          - 'sample_time_increment'
  - 'W':
    value:
      initial: 3.9270
      goal: [-1]
      range: [0, 6.2832]
      overflow: 'wrap'
    implicit_grid:
      active: true
      resolution: 0.26180
      size: 24
    control:
      - add:
        - 'W'
        - multiply:
          - 'U'
          - 'sample_time_increment'

controls:
  - 'V':
    value:
      initial: 0.0
      range: [0.0, 1.0]
  - 'U':
    value:
      initial: 0.0
      range: [-0.105, 0.105]

