states:
  - name: 'X'
    value:
      initial: 0.0
      goal: 5.0
      goal_radius: 0.3
    implicit_grid:
      active: true
      resolution: 0.15
      size: 50

  - name: 'Y'
    value:
      initial: 0.0
      goal: 5.0
      goal_radius: 0.3
    implicit_grid:
      active: true
      resolution: 0.15
      size: 50

  - name: 'W'
    value:
      initial: 0.0
      goal: 0.0
      goal_radius: -1.0
    implicit_grid:
      active: true
      resolution: 0.62832
      size: 10

controls:
  - name: 'V'
    value:
      initial: 0.0
  - name: 'U'
    value:
      initial: 0.0

