states:
  - name: 'X'
    value:
      initial: 122.0
      goal: [62.5, 67.5]
    implicit_grid:
      active: true
      resolution: 1.0
      size: 141

  - name: 'Y'
    value:
      initial: 122.0
      goal: [62.5, 67.5]
    implicit_grid:
      active: true
      resolution: 1.0
      size: 141

  - name: 'W'
    value:
      initial: 3.9270
      goal: false
    implicit_grid:
      active: true
      resolution: 0.31416
      size: 20

  - name: 'T'
    value:
      initial: 300.0
      goal: false
    implicit_grid:
      active: false

controls:
  - name: 'V'
    value:
      initial: 0.0
      range: [0.0, 1.0]
  - name: 'U'
    value:
      initial: 0.0
      range: [-0.105, 0.105]

