states:
  - name: 'X'
    value:
      initial: 122.0
      goal: [65.0]
      range: [0.0, 141.0]
    implicit_grid:
      active: true
      resolution: 1.0
      size: 141

  - name: 'Y'
    value:
      initial: 20.0
      goal: [65.0]
      range: [0.0, 141.0]
    implicit_grid:
      active: true
      resolution: 1.0
      size: 141

  - name: 'W'
    value:
      initial: 3.9270
      goal: [-1.0]
      range: [0.0, 6.2832]
    implicit_grid:
      active: true
      resolution: 0.26180
      size: 24

controls:
  - name: 'V'
    value:
      initial: 0.0
      range: [0.0, 1.0]
  - name: 'U'
    value:
      initial: 0.0
      range: [-0.105, 0.105]

